import Link from "next/link";
import type { ReactNode } from "react";
import "server-only";

export const revalidate = 0;

function Section({ title, children }: { title: string; children: ReactNode }) {
  return <section className="border-t border-[var(--line)] pt-8 pb-6"><h2 className="ua-h3 mb-4">{title}</h2><div className="space-y-3 text-sm leading-7 text-[var(--ink2)] max-w-3xl">{children}</div></section>;
}

export default function PrivacyPage() {
  return (
    <main className="ua-page">
      <header className="hero border-b border-[var(--line)]"><div className="page-shell"><div className="eyebrow mb-4">Privacy Policy</div><h1 className="ua-h1">How personal data is handled</h1><p className="lead mt-4 max-w-3xl">This notice explains the controller, data categories, purposes, legal bases, processors, retention approach, security safeguards and rights that apply to Urd Atlas users.</p></div></header>
      <div className="page-shell py-12"><div style={{maxWidth:"800px"}}>
        <Section title="1. Controller and contact"><p>The data controller for Urd Atlas is <strong>MARTIN BALSTAD</strong>, organisation number 937 581 254, Norway.</p><p>Privacy, access, deletion, support and legal requests can be sent to <a href="mailto:support@urdatlas.com" className="text-link">support@urdatlas.com</a>.</p></Section>
        <Section title="2. Scope"><p>This notice applies to the public website, subscriber accounts, dashboard, authenticated JSON delivery, billing workflows, support communication and operational/security logging used to provide Urd Atlas.</p><p>Public blockchain observations published by Urd Atlas describe blockchain activity and are not collected in order to profile Urd Atlas customers.</p></Section>
        <Section title="3. Data categories"><ul className="list-disc pl-5 space-y-1"><li>Account identifiers, email address and authentication-linked profile data.</li><li>Subscription, plan, billing-state and entitlement metadata.</li><li>API-key metadata such as key ID, non-secret prefix/last four characters, status and last-used information; full API-key secrets are not designed to be stored recoverably in plaintext.</li><li>Request and security metadata needed for delivery, rate limiting, abuse prevention, troubleshooting and incident response.</li><li>Support, privacy or legal correspondence that you choose to send.</li><li>Provider-side billing/payment data processed by Stripe; Urd Atlas does not store payment-card details directly.</li></ul></Section>
        <Section title="4. Purposes and legal bases"><p><strong>Contract / steps at your request:</strong> account access, subscriber entitlements, API delivery, checkout, billing and customer-portal functionality are processed as necessary to provide the service you request.</p><p><strong>Legitimate interests:</strong> bounded operational logging, service security, abuse prevention, rate limiting, reliability diagnostics and support investigation are processed to protect and operate the service, balanced against user privacy.</p><p><strong>Legal obligation:</strong> billing/business records and disclosures may be retained or processed where Norwegian or other applicable law requires it.</p><p><strong>Consent:</strong> Urd Atlas does not rely on behavioral-advertising consent to operate the product. If an optional feature later requires consent, that purpose should be stated separately rather than silently folded into this notice.</p></Section>
        <Section title="5. Authentication and billing"><p>Clerk provides authentication and session handling. Stripe provides checkout, subscription billing, invoices and customer-portal functions. Their processing is also governed by their own privacy terms.</p><p>A current list of production providers and the principal data categories they handle is published at <Link href="/subprocessors" className="text-link">Subprocessors</Link>.</p></Section>
        <Section title="6. API access and security logging"><p>Authenticated subscriber delivery requires API keys. Urd Atlas may process key identifiers, status, account linkage, request path, request ID, response status, timing and bounded client/request metadata needed for entitlement enforcement, security, rate limiting and customer support.</p><p>Ordinary operational evidence should not retain full API secrets, complete browser sessions, payment-card data, unbounded headers or unnecessary personal content.</p></Section>
        <Section title="7. Retention"><p>Retention is tied to the operational/legal purpose rather than indefinite collection. Active account and entitlement records are kept while the account/service relationship is active and for a reasonable period afterward where needed for billing, dispute handling, security or legal records.</p><p>Billing references may be retained for the period required by applicable accounting/tax law. Security and request logs are kept only as long as reasonably needed for service operation, abuse investigation and incident evidence. Support correspondence may be retained while a matter is open and for a reasonable follow-up period.</p><p>Where a user has a valid deletion right, data that is not required for an overriding legal/security purpose should be deleted or de-linked after the request is verified.</p></Section>
        <Section title="8. International processing"><p>Some service providers may process data in jurisdictions outside Norway or the EEA as part of their global infrastructure. Where GDPR transfer rules apply, the relevant provider/controller relationship must rely on an applicable transfer mechanism, such as an adequacy decision or contractual safeguards provided by the processor.</p></Section>
        <Section title="9. Security"><p>Urd Atlas uses HTTPS delivery, authentication, entitlement checks, API-key hashing, route protections, rate limiting and provider-managed encryption controls as part of its security model. No internet service can guarantee absolute security.</p><p>More detail is available at <Link href="/security" className="text-link">Security</Link> and <Link href="/security/reporting" className="text-link">Responsible Disclosure</Link>.</p></Section>
        <Section title="10. Security incidents"><p>Security incidents are assessed separately from ordinary service/data-freshness issues. Where GDPR or other applicable law requires notification to a regulator or affected individuals, Urd Atlas follows the applicable threshold and timing requirements and communicates the nature of the incident, likely consequences and mitigation where required.</p></Section>
        <Section title="11. Your rights"><p>Depending on the applicable law and circumstances, you may have rights to access, rectification, erasure, restriction, objection and data portability, and to withdraw consent where consent is the legal basis.</p><p>Requests can be sent to <a href="mailto:support@urdatlas.com" className="text-link">support@urdatlas.com</a>. Identity may need to be verified before account-linked information is disclosed or deleted.</p><p>You also have the right to complain to the Norwegian Data Protection Authority (Datatilsynet) or another competent supervisory authority where applicable.</p></Section>
        <Section title="12. Advertising and profiling"><p>Urd Atlas does not require behavioral advertising or sale of user profiles to provide the service. If analytics/diagnostics are used, their intended purpose is product operation, reliability, security and aggregate performance rather than advertising resale.</p></Section>
        <Section title="13. Related documents"><p>See <Link href="/terms" className="text-link">Terms of Service</Link>, <Link href="/subprocessors" className="text-link">Subprocessors</Link>, <Link href="/security" className="text-link">Security</Link>, <Link href="/status" className="text-link">Status</Link> and the <Link href="/trust" className="text-link">Trust center</Link>.</p></Section>
      </div></div>
    </main>
  );
}
