import Link from "next/link";

export const revalidate = 0;

export default function SecurityPage() {
  return (
    <main className="ua-page">
      <header className="hero border-b border-[var(--line)]"><div className="page-shell"><div className="eyebrow mb-4">Security</div><h1 className="ua-h1">Security controls and operating safeguards</h1><p className="lead mt-4 max-w-3xl">A concise public description of how Urd Atlas protects authenticated access, credentials, subscriber state and production delivery.</p></div></header>
      <div className="page-shell py-12 max-w-4xl space-y-10">
        <section><h2 className="ua-h3">Transport and storage</h2><div className="mt-4 space-y-3 text-sm leading-7 text-[var(--ink2)]"><p>Public and authenticated web traffic is served over HTTPS. The production Supabase PostgreSQL project used for account, entitlement and API-key metadata reports PostgreSQL SSL enabled with a minimum protocol of TLS 1.2. Supabase documents project data as encrypted at rest by default.</p><p>Vercel serves and deploys the web application. Vercel documents platform data as encrypted at rest with AES-256 and encrypted in transit with HTTPS/TLS.</p><p>Upstash is used only for bounded pre-authentication rate-limit state. The application connects through the provider REST client and fails closed in production if that backend is unavailable. Upstash documents encryption at rest as a plan-specific Prod Pack control, so Urd Atlas does not claim that control as enabled without account-side evidence. This rate-limit store is not the system of record for subscriptions, account entitlements, API-key secrets or published subscriber files.</p><p>Urd Atlas does not store customer payment-card data directly; Stripe handles payment-card processing.</p></div></section>
        <section><h2 className="ua-h3">Authentication and API keys</h2><div className="mt-4 space-y-3 text-sm leading-7 text-[var(--ink2)]"><p>Clerk provides account authentication and session handling. Subscriber file delivery requires an active entitlement and an API key.</p><p>API-key secrets are generated from cryptographically secure random bytes. Urd Atlas stores a salted scrypt hash for verification plus a non-secret prefix and final four characters for identification. The full secret is returned at creation time and is not designed to be recoverable later in plaintext.</p><p>Accounts are limited to two non-revoked API keys at a time. Keys can be revoked from the account flow and inactive subscriptions are denied authenticated file access.</p></div></section>
        <section><h2 className="ua-h3">Abuse prevention and request controls</h2><div className="mt-4 space-y-3 text-sm leading-7 text-[var(--ink2)]"><p>Protected routes use entitlement checks, same-origin protection where appropriate, request logging and rate limiting. Production pre-auth rate limiting fails closed if its configured backend is unavailable.</p><p>Current public limit semantics are documented at <Link href="/api-docs/rate-limits" className="text-link">API Rate Limits</Link>.</p></div></section>
        <section><h2 className="ua-h3">Change and incident process</h2><div className="mt-4 space-y-3 text-sm leading-7 text-[var(--ink2)]"><p>Production-bound code and methodology changes are tracked in Git and are expected to pass the applicable build, test, audit and publication-integrity gates before release.</p><p>Security incidents are handled separately from ordinary data-freshness incidents. Where applicable law requires regulator or affected-user notification, Urd Atlas follows the applicable legal threshold and timing rather than applying one universal notification clock to every operational event.</p><p>Persistent customer-impacting incidents should be reflected on <Link href="/status" className="text-link">Status</Link>.</p></div></section>
        <section><h2 className="ua-h3">Responsible disclosure</h2><p className="mt-4 text-sm leading-7 text-[var(--ink2)]">Suspected security vulnerabilities should be reported through the <Link href="/security/reporting" className="text-link">responsible-disclosure process</Link>. Do not access other customers&apos; data, perform denial-of-service testing, or exfiltrate data to demonstrate a finding.</p></section>
        <section><h2 className="ua-h3">Assurance boundary</h2><div className="mt-4 space-y-3 text-sm leading-7 text-[var(--ink2)]"><p>Urd Atlas maintains SOC2-style internal process documentation for access control, change management, incident response, recovery, vendor review and security-review cadence. This is not a SOC 2 certification, external attestation or formal assurance report.</p><p>The statements above distinguish controls verified from the production account, controls documented as provider defaults, and controls that are plan-specific. Urd Atlas does not infer a plan-specific control merely because a provider offers it.</p></div></section>
      </div>
    </main>
  );
}
