import Link from "next/link";

export const revalidate = 0;

function Code({ children }: { children: string }) { return <pre className="overflow-x-auto rounded-xl border border-[var(--line)] p-4 text-xs leading-6"><code>{children}</code></pre>; }

export default function EvidenceScorePage() {
  return (
    <main className="ua-page">
      <header className="hero border-b border-[var(--line)]"><div className="page-shell"><div className="eyebrow mb-4">Methodology</div><h1 className="ua-h1">Evidence score: exact public calculation</h1><p className="lead mt-4 max-w-3xl">The current score is deterministic, profile-aware and label-specific. It measures support for a published row; it is not a calibrated probability that the label is true.</p></div></header>
      <div className="page-shell py-12 max-w-5xl space-y-10 text-sm leading-7 text-[var(--ink2)]">
        <section><h2 className="ua-h3 text-[var(--ink)]">1. Composite score</h2><p className="mt-3">Current method: <code>confidence_v3_l2_capacity_required</code>. Public terminology is <strong>Evidence score</strong>; the legacy API field remains <code>confidence.confidence_score</code> for compatibility.</p><div className="mt-4"><Code>{`evidence_score = clamp01(sqrt(data_quality_score * label_confidence_score))\npublication gate = 0.40\nif evidence_score < 0.40 => public label = UNKNOWN/DEGRADED`}</Code></div><p className="mt-3">If data quality exists but label confidence is unavailable, the legacy builder can fall back to the data-quality score. Normal named-state publication still remains subject to the gate and regime rules.</p></section>
        <section><h2 className="ua-h3 text-[var(--ink)]">2. Data-quality score</h2><div className="mt-4"><Code>{`data_quality_score = weighted_mean(\n  0.35 * current_row_coverage,\n  0.25 * recent_metric_coverage_30d,\n  0.15 * recent_density_30d,\n  0.15 * history_depth_180d,\n  0.10 * freshness_asof\n)`}</Code></div><p className="mt-3">Only finite/available components enter the denominator. Current-row coverage is the fraction of required profile metrics present on the latest supporting row. Recent metric coverage is the mean required-metric coverage over the last 30 calendar days. Recent density is <code>min(1, observed distinct days / 30)</code>. History depth is <code>min(1, distinct history days / 180)</code>.</p><p className="mt-3">Freshness is 1.0 through the expected lag (BTC/ETH 1 day; ARB/BASE 7 days), decays to 0.70 at the soft boundary (2 days for L1, 10 days for L2), then linearly to 0 at the hard boundary (4 days for L1, 15 days for L2).</p></section>
        <section><h2 className="ua-h3 text-[var(--ink)]">3. Shared primitive functions</h2><div className="mt-4"><Code>{`high_margin(score) = clamp01((score - 67) / 33)\nlow_margin(score)  = clamp01((33 - score) / 33)\nneutrality(score)  = clamp01(1 - abs(score - 50) / 17)\ntrend_strength(expected) = 1.0 if matching trend, 0.35 if FLAT, else 0.0\npersistence_score = clamp01(label_run_days / 7) when prior-label run length is available`}</Code></div></section>
        <section><h2 className="ua-h3 text-[var(--ink)]">4. Driver strength</h2><p className="mt-3">Each eligible driver is scored from its published robust-z, 90-day percentile and 7d-vs-30d momentum. Directionally contradictory drivers are excluded for high-side or low-side labels.</p><div className="mt-4"><Code>{`z_score   = clamp01(abs(z_robust) / 3)\npct_score = clamp01(abs(pct_90d - 50) / 50)\nmom_score = clamp01(abs(momentum_7d_vs_30d) / 2)\ndriver_i  = 0.55*z_score + 0.30*pct_score + 0.15*mom_score\ndriver_strength = mean(up to 3 strongest eligible driver_i values)`}</Code></div></section>
        <section><h2 className="ua-h3 text-[var(--ink)]">5. Label-specific score</h2><div className="mt-4 space-y-5"><Code>{`HEATING = weighted_mean(\n  0.35*rule_margin, 0.25*driver_strength_demand,\n  0.20*trend_strength_demand, 0.10*axis_coherence,\n  0.10*persistence_score\n)`}</Code><Code>{`CONGESTED = weighted_mean(\n  0.35*rule_margin, 0.25*driver_strength_friction_capacity,\n  0.20*axis_coherence, 0.10*severity_margin,\n  0.10*persistence_score\n)`}</Code><Code>{`CHEAP = weighted_mean(\n  0.35*rule_margin, 0.25*driver_strength_friction_low_side,\n  0.20*no_capacity_pressure, 0.10*axis_coherence,\n  0.10*persistence_score\n)`}</Code><Code>{`STABLE = weighted_mean(\n  0.45*neutrality_score, 0.25*no_strong_driver_score,\n  0.20*axis_coherence, 0.10*persistence_score\n)`}</Code></div><p className="mt-3">Unavailable persistence is excluded from the weighted denominator rather than imputed.</p></section>
        <section><h2 className="ua-h3 text-[var(--ink)]">6. Rule margins and coherence</h2><div className="mt-4"><Code>{`HEATING rule_margin = max(high_margin(demand_raw), 1 if raw Demand axis is HIGH+ and trend is HEATING else 0)\nCONGESTED rule_margin = max(min(high_margin(friction_raw), high_margin(capacity_raw)), 1 if the raw congestion-axis rule is met else 0)\nCHEAP rule_margin = max(min(low_margin(friction_raw), 1-high_margin(capacity_raw)), 1 if raw Friction is LOW and Capacity is not HIGH else 0)\nSTABLE rule_margin = mean(neutrality(demand_raw), neutrality(friction_raw), neutrality(capacity_raw))`}</Code></div><p className="mt-3">CONGESTED severity margin is the maximum high-margin of raw Friction and Capacity. CHEAP no-capacity-pressure support is <code>1 - high_margin(capacity_raw)</code>. STABLE no-strong-driver support is <code>1 - driver_strength</code> (or 1 when no driver strength exists).</p><p className="mt-3">Axis coherence penalizes evidence that directly contradicts the candidate label. HEATING reduces coherence for strong cheap/congestion counter-evidence; CONGESTED reduces it for low-friction evidence; CHEAP reduces it for high friction/capacity; STABLE is <code>clamp01(1 - max(abs(axis_raw-50)/50))</code>.</p></section>
        <section><h2 className="ua-h3 text-[var(--ink)]">7. Interpretation boundary</h2><p className="mt-3">An Evidence score of 0.80 means stronger support than 0.50 under this deterministic methodology. It does <strong>not</strong> mean “80% probability the label is correct”. No external ground-truth calibration currently supports probability language.</p><p className="mt-3">Threshold rationale and perturbation tests are documented in <Link href="/validation" className="text-link">Validation</Link> and the public methodology. The score uses raw scorecard/regime evidence for label confidence; the customer-facing display score can be pulled toward 50 after confidence degradation and is not recursively used to calculate confidence.</p></section>
      </div>
    </main>
  );
}
