import Link from "next/link";
import type { ReactNode } from "react";
import "server-only";

export const revalidate = 0;

function InlineCode({ children }: { children: string }) { return <code className="code-block inline-block px-2 py-0.5 text-[12px]">{children}</code>; }
function Section({ title, children }: { title: string; children: ReactNode }) { return <section className="border-t border-[var(--line)] pt-8 pb-6"><h2 className="ua-h3 mb-4">{title}</h2><div className="space-y-3 text-sm leading-7 text-[var(--ink2)] max-w-3xl">{children}</div></section>; }

export default function TermsPage() {
  return (
    <main className="ua-page">
      <header className="hero border-b border-[var(--line)]"><div className="page-shell"><div className="eyebrow mb-4">Terms of Service</div><h1 className="ua-h1">Terms of Service</h1><p className="lead mt-4 max-w-3xl">These Terms govern the Urd Atlas public website, subscriber account, billing and authenticated data-delivery service.</p></div></header>
      <div className="page-shell py-12"><div style={{maxWidth:"800px"}}>
        <Section title="1. Service description"><p>Urd Atlas is a descriptive on-chain reference-data product. It provides public explanatory pages and reference endpoints, subscriber account functionality, and authenticated delivery of published Gold, Derived, Meta and Briefs artifacts.</p><p>The service describes observed network conditions. It is not an investment-advice, trading-signal, portfolio-management or forecasting service.</p></Section>
        <Section title="2. Legal operator"><p>Urd Atlas is operated by <strong>MARTIN BALSTAD</strong>, organisation number 937 581 254, Norway. The public operator profile is available at <Link href="/operator" className="text-link">/operator</Link>.</p></Section>
        <Section title="3. No investment or trading advice"><p>No page, API response, JSON artifact, score, regime label, driver, Brief or other output is an instruction or recommendation to buy, sell, hold, rebalance, hedge or take another financial action.</p><p>Customers remain solely responsible for their own analysis, model design, controls and decisions.</p></Section>
        <Section title="4. Plans, price and billing"><p>Current standard monthly list prices are shown on the pricing surface before checkout. Basic is $49/month for one selected chain; Pro is $149/month for all four supported chains and the full published archive. Urd Atlas does not charge a separate setup fee or a separate per-request usage fee for these standard plans.</p><p>Stripe is used for checkout, subscription billing, invoices, approved refunds and customer-portal workflows. Payment-card details are handled by Stripe and are not stored directly by Urd Atlas.</p><p>Any taxes that Urd Atlas is legally/configurationally required to collect must be presented in the checkout confirmation flow before the purchase is completed. Tax treatment can depend on customer location and business/customer status.</p></Section>
        <Section title="5. Renewal, cancellation and refunds"><p>Paid subscriptions renew automatically at the billing interval shown at checkout unless cancelled before the next renewal.</p><p>If cancellation is scheduled for the end of the paid period, subscriber access normally remains active until that period ends. An immediate cancellation, refund or entitlement suspension may end dashboard, API-key and subscriber-file access when the subscription becomes inactive.</p><p>Fees already charged are generally non-refundable for partial periods except where applicable law requires otherwise or Urd Atlas explicitly approves a refund.</p></Section>
        <Section title="6. Data retained after cancellation"><p>Subscriber files that were lawfully downloaded while the customer had an active entitlement may be retained and used for that customer&apos;s own internal analytical or business purposes after cancellation. Cancellation ends the right to obtain new subscriber files, newly published days, later corrections/revisions or other subscriber-only delivery unless access is reactivated.</p><p>This retention right does not permit resale, redistribution, sublicensing, public mirroring or operation of a substitutive data service.</p></Section>
        <Section title="7. Upgrades and downgrades"><p>Where plan switching is enabled, an upgrade from Basic to Pro may take effect immediately and may generate a prorated charge or credit through Stripe. A downgrade should normally take effect at the next renewal so already-paid higher-tier access is not removed mid-period.</p><p>A downgrade from Pro to Basic requires a selected entitled chain for the next Basic period. The exact amount charged or credited is the amount displayed by Stripe before the plan change is confirmed.</p></Section>
        <Section title="8. Publication cadence and availability"><p>Urd Atlas checks and publishes through two primary daily production windows around <strong>08:00 and 20:00 Europe/Oslo</strong>, with automated catch-up checks if a scheduled trigger is missed. These are operating targets rather than a contractual timestamp SLA.</p><p>Expected observation lag is approximately one day for Bitcoin/Ethereum and seven days for Arbitrum/Base. Upstream source timing can delay publication. Urd Atlas does not fabricate a new observation when no complete source day exists.</p><p>See <Link href="/status" className="text-link">Status</Link> and <Link href="/methodology/sources" className="text-link">Source-day policy</Link>.</p></Section>
        <Section title="9. Internal-use license"><p>Subject to these Terms and the applicable entitlement, Urd Atlas grants a limited, non-exclusive, non-transferable and non-sublicensable license to use subscriber outputs for the customer&apos;s own internal personal or business analysis.</p><p>No ownership interest in Urd Atlas, its compiled reference-data product, methodology, presentation, authenticated outputs or documentation is transferred by purchasing access.</p></Section>
        <Section title="10. Excerpts and attribution"><p>Customers may include limited excerpts, derived charts, summary statistics or individual Urd Atlas labels in their own external reports and presentations where the excerpt does not substitute for the paid dataset. Such use must include reasonably visible attribution such as <strong>Source: Urd Atlas</strong> and should preserve the relevant chain/date/methodology context where material.</p><p>Full or systematic subscriber datasets, historical archives, authenticated JSON files or API-proxy access may not be publicly redistributed, resold, sublicensed, mirrored or repackaged without written permission.</p></Section>
        <Section title="11. Automation, models and AI"><p>Customers may use Urd Atlas as an input to internal analytics, data pipelines, statistical models, machine-learning workflows and internal software/agents within their entitlement and these Terms.</p><p>Urd Atlas does not endorse or control any downstream automated financial action a customer chooses to build. The customer is responsible for validation, controls and legal/regulatory requirements applicable to such a system.</p><p>Subscriber outputs may not be used to create or operate a competing or substitutive commercial reference-data product, third-party signal feed, public API, white-labelled service or dataset that materially republishes Urd Atlas&apos; paid data.</p></Section>
        <Section title="12. Prohibited uses"><p>You may not bypass entitlements, authentication, route protections or rate limits; share secret API credentials outside the authorized account/organization; access another customer&apos;s data; remove material provenance in a misleading way; or use the service unlawfully.</p><p>Current rate-limit behavior is documented at <Link href="/api-docs/rate-limits" className="text-link">API Rate Limits</Link>.</p></Section>
        <Section title="13. API and schema compatibility"><p>Published artifacts and documented endpoints are versioned. Planned breaking changes target at least 30 calendar days&apos; notice, subject to shorter timelines where a critical security, legal, corruption-repair or data-integrity fix requires it.</p><p>See <Link href="/api-docs/versioning" className="text-link">Versioning and breaking changes</Link> and <Link href="/methodology/changelog" className="text-link">Methodology Changelog</Link>.</p></Section>
        <Section title="14. Corrections and revisions"><p>Published artifacts may be corrected when an upstream-data, implementation or explanatory defect is confirmed. Material archival changes should be versioned or logged with the affected chains/dates, whether history changed, and whether customers should re-pull cached files.</p></Section>
        <Section title="15. Security"><p>Customers must safeguard their account and API keys and promptly revoke credentials they believe are compromised. Urd Atlas may suspend keys or access to protect the service, enforce entitlements or respond to abuse/security incidents.</p><p>See <Link href="/security" className="text-link">Security</Link> and <Link href="/security/reporting" className="text-link">Responsible Disclosure</Link>.</p></Section>
        <Section title="16. Intellectual property"><p>Unless otherwise stated, Urd Atlas&apos; site structure, explanatory text, methodology presentation, brand elements, compiled reference-data artifacts, documentation and authenticated outputs are protected by applicable intellectual-property and contract rights.</p></Section>
        <Section title="17. Disclaimer of warranties"><p>The service is provided on an “as is” and “as available” basis. Urd Atlas does not guarantee uninterrupted availability, error-free data, fitness for a particular purpose, future outcomes or that an upstream blockchain-data provider will publish on a particular timetable.</p></Section>
        <Section title="18. Limitation of liability"><p>To the maximum extent permitted by applicable law, Urd Atlas and its operator are not liable for indirect, incidental, special, consequential or business losses arising from use of the service, API, subscriber data or published reference data.</p><p>Nothing in these Terms excludes liability that cannot lawfully be excluded.</p></Section>
        <Section title="19. Suspension and termination"><p>Access may be suspended or terminated for material breach, non-payment, security risk, abuse or unlawful use. Termination ends future subscriber delivery rights, subject to the post-cancellation internal retention right for files already lawfully downloaded.</p></Section>
        <Section title="20. Planned service wind-down"><p>If Urd Atlas plans to permanently discontinue the subscriber service, it will aim to provide at least 30 calendar days&apos; notice where reasonably practicable. During an announced export window, active customers should be given a reasonable opportunity to retrieve the published data within their then-current entitlement.</p><p>No promise is made that public hosting will remain permanently available after service closure. Files already lawfully downloaded remain subject to Section 6.</p></Section>
        <Section title="21. Security and personal-data incidents"><p>Security incidents are assessed under the applicable legal and operational requirements. Where the law requires notification to a regulator or affected individuals, Urd Atlas will notify in accordance with the applicable threshold and timing and provide the information required by law. Ordinary availability or data-freshness incidents are not automatically personal-data breaches.</p></Section>
        <Section title="22. Governing law"><p>These Terms and the service relationship are governed by the laws of Norway, subject to any mandatory consumer or other rights that applicable law does not permit the parties to exclude.</p></Section>
        <Section title="23. Changes to Terms"><p>These Terms may be updated as the service changes. Material contract changes should be communicated through the public service/documentation surfaces or account communication where appropriate. The latest published Terms govern ongoing use unless applicable law requires otherwise.</p></Section>
        <Section title="24. Contact"><p>Support, billing, cancellation, privacy and legal requests: <a href="mailto:support@urdatlas.com" className="text-link">support@urdatlas.com</a>.</p><p>Related documents: <Link href="/privacy" className="text-link">Privacy</Link>, <Link href="/trust" className="text-link">Trust center</Link>, <Link href="/service" className="text-link">Service expectations</Link>, <Link href="/api-docs" className="text-link">API Docs</Link>.</p></Section>
      </div></div>
    </main>
  );
}
