import Link from "next/link";
import { CURRENT_CONFIDENCE_METHOD, CURRENT_META_METHODOLOGY_VERSION } from "@/lib/methodologyVersion";

export const revalidate = 0;

const rows = [
  ["2026-08-27", "contract/documentation hardening", "Trust, security, API/versioning, source and Evidence documentation", "No analytical change", "No", "No", <>Aligned public documentation with the currently published Meta contract: <code>{CURRENT_META_METHODOLOGY_VERSION}</code> and <code>{CURRENT_CONFIDENCE_METHOD}</code>. This entry records the documentation alignment date; it does not claim the active confidence method was first introduced on this date.</>],
  ["2026-08-13", "historical textual correction", "Meta day files and aggregated Meta windows", "No", "Yes — descriptive status text only", "Re-pull affected Meta if cached before correction", <>Corrected a grammatical fallback defect in <code>status.one_liner</code> / status-note text. No regime, score, confidence, driver or underlying metric changed.</>],
  ["2026-07-05", "docs-only contract coverage fix", "Field Dictionary and audit gates", "No", "No", "No", <>Expanded Gold-field and per-chain axis documentation and added implementation-sync gates.</>],
  ["2026-05-18", "methodology update + historical republish", "Meta and Briefs", "Confidence v2 / Meta 1.1", "Yes", "Re-pull if cached before the republish", <>Introduced profile-aware data quality and label-specific confidence; structurally non-applicable fields were excluded from denominators and raw evidence was separated from confidence-degraded display scores.</>],
  ["2026-04-21", "methodology/documentation foundation", "Methodology, fields, boundaries, integrity and API docs", "No additional analytical bump", "No", "No", <>Introduced the structured public trust layer, interpretation boundaries, field contract and provenance documentation.</>],
] as const;

export default function MethodologyChangelogPage() {
  return <main className="ua-page">
    <header className="hero border-b border-[var(--line)]"><div className="page-shell"><div className="eyebrow mb-4">Methodology</div><h1 className="ua-h1">Methodology Changelog</h1><p className="lead mt-4 max-w-3xl">Customer-facing record of analytical methodology, contract, interpretation and historical-republish changes.</p><div className="mt-5 text-sm text-[var(--ink2)]">Current Meta methodology: <code>{CURRENT_META_METHODOLOGY_VERSION}</code> · Current confidence method: <code>{CURRENT_CONFIDENCE_METHOD}</code></div></div></header>
    <div className="page-shell py-12 max-w-7xl space-y-10">
      <section><h2 className="ua-h3">How to read the log</h2><p className="mt-3 max-w-4xl text-sm leading-7 text-[var(--ink2)]">Output-affecting methodology changes are separated from docs-only changes. A historical republish states whether previously published artifacts changed and whether subscribers who cache local copies should re-pull them. Breaking API/schema compatibility is governed separately by <Link href="/api-docs/versioning" className="text-link">Versioning and breaking changes</Link>.</p></section>
      <section><div className="overflow-x-auto"><table className="w-full min-w-[1200px] text-left text-xs leading-6"><thead><tr className="border-b border-[var(--line)]"><th className="py-3 pr-4">Date</th><th className="py-3 pr-4">Class</th><th className="py-3 pr-4">Affected</th><th className="py-3 pr-4">Methodology impact</th><th className="py-3 pr-4">History changed?</th><th className="py-3 pr-4">Subscriber action</th><th className="py-3">Summary</th></tr></thead><tbody>{rows.map(([date,cls,affected,method,history,action,summary])=><tr key={`${date}-${cls}`} className="border-b border-[var(--line)] align-top"><td className="py-4 pr-4 font-mono">{date}</td><td className="py-4 pr-4">{cls}</td><td className="py-4 pr-4 text-[var(--ink2)]">{affected}</td><td className="py-4 pr-4 text-[var(--ink2)]">{method}</td><td className="py-4 pr-4 text-[var(--ink2)]">{history}</td><td className="py-4 pr-4 text-[var(--ink2)]">{action}</td><td className="py-4 text-[var(--ink2)]">{summary}</td></tr>)}</tbody></table></div></section>
      <section><h2 className="ua-h3">Future non-docs changes must state</h2><ul className="mt-3 list-disc pl-5 space-y-2 text-sm leading-7 text-[var(--ink2)]"><li>Exact affected chains, dates, fields and artifact genres.</li><li>Old and new methodology/schema identifiers where applicable.</li><li>Whether historical files were regenerated or replaced.</li><li>Whether determinism/provenance identity changed.</li><li>Whether subscribers should re-pull cached artifacts or change parsers.</li></ul></section>
    </div>
  </main>;
}
