from pathlib import Path

regime_path = Path('api/regime_engine.py')
text = regime_path.read_text(encoding='utf-8')
old = '''    if label == "HEATING":\n        ok = bool(high(d) and heating(d))\n        return ok, details, "regime axes require informative demand high with HEATING trend."\n'''
new = '''    if label == "HEATING":\n        # Mirror the ETH L1 classifier's supplemental calldata corroboration path.\n        # Without this, a valid ETH HEATING candidate can be produced by the\n        # classifier and then incorrectly demoted to STABLE by reconciliation.\n        ruleset_id = str(regime.get("ruleset_id") or "")\n        calldata = ((regime.get("signals") or {}).get("nonempty_calldata_share") or {})\n        calldata_heating = bool(\n            ruleset_id.startswith("eth_l1")\n            and bool(calldata.get("informative", True))\n            and str(calldata.get("trend")) == "HEATING"\n        )\n        ok = bool(high(d) and (heating(d) or calldata_heating))\n        return ok, details, (\n            "regime axes require informative high demand with HEATING trend "\n            "or Ethereum supplemental calldata HEATING corroboration."\n        )\n'''
if old not in text:
    raise SystemExit('Expected HEATING reconciliation block not found')
regime_path.write_text(text.replace(old, new, 1), encoding='utf-8')

test_path = Path('tests/test_regime_reconciliation.py')
test_path.parent.mkdir(parents=True, exist_ok=True)
test_path.write_text('''import unittest\n\nfrom api.regime_engine import reconcile_regime_with_scorecard\n\n\ndef axis(high="NORMAL", low="NORMAL", trend="FLAT", informative=1):\n    return {\n        "band_high": high,\n        "band_low": low,\n        "trend": trend,\n        "informative_count": informative,\n    }\n\n\ndef unsupported_scorecard():\n    return {\n        "dimensions": {\n            "demand": {"score": 50.0, "level": "Normal"},\n            "friction": {"score": 50.0, "level": "Normal"},\n            "capacity": {"score": 50.0, "level": "Balanced"},\n        }\n    }\n\n\nclass RegimeReconciliationTests(unittest.TestCase):\n    def base_regime(self, ruleset_id):\n        return {\n            "chain": "ethereum" if ruleset_id.startswith("eth_l1") else "base",\n            "ruleset_id": ruleset_id,\n            "label": "HEATING",\n            "asof_date": "2026-08-11",\n            "axes": {\n                "demand": axis(high="HIGH", trend="COOLING"),\n                "friction": axis(),\n                "capacity": axis(),\n            },\n            "signals": {\n                "nonempty_calldata_share": {"informative": True, "trend": "HEATING"}\n            },\n            "drivers": [],\n        }\n\n    def test_eth_calldata_heating_is_preserved(self):\n        out = reconcile_regime_with_scorecard(self.base_regime("eth_l1_v2"), unsupported_scorecard())\n        self.assertEqual(out["label"], "HEATING")\n        self.assertFalse(out["sanity"]["adjusted"])\n        self.assertEqual(out["sanity"]["support_basis"], "regime_axes")\n\n    def test_non_eth_does_not_inherit_calldata_exception(self):\n        out = reconcile_regime_with_scorecard(self.base_regime("l2_v1"), unsupported_scorecard())\n        self.assertEqual(out["label"], "STABLE")\n        self.assertTrue(out["sanity"]["adjusted"])\n\n    def test_eth_without_calldata_heating_is_still_demoted(self):\n        regime = self.base_regime("eth_l1_v2")\n        regime["signals"]["nonempty_calldata_share"]["trend"] = "COOLING"\n        out = reconcile_regime_with_scorecard(regime, unsupported_scorecard())\n        self.assertEqual(out["label"], "STABLE")\n        self.assertTrue(out["sanity"]["adjusted"])\n\n\nif __name__ == "__main__":\n    unittest.main()\n''', encoding='utf-8')

ci_path = Path('.github/workflows/ci.yml')
ci = ci_path.read_text(encoding='utf-8')
needle = '''      - name: Run pipeline determinism gate\n        run: npm run check:pipeline-determinism\n'''
insert = '''      - name: Run regime reconciliation regression tests\n        working-directory: .\n        run: python -m unittest discover -s tests -p 'test_*.py'\n\n      - name: Run pipeline determinism gate\n        run: npm run check:pipeline-determinism\n'''
if needle not in ci:
    raise SystemExit('Expected CI insertion point not found')
ci_path.write_text(ci.replace(needle, insert, 1), encoding='utf-8')
