import Link from "next/link";

export const revalidate = 0;

export default function ServicePage() {
  return (
    <main className="ua-page">
      <header className="hero border-b border-[var(--line)]"><div className="page-shell"><div className="eyebrow mb-4">Public service policy</div><h1 className="ua-h1">Service Expectations, Support & Revisions</h1><p className="lead mt-4 max-w-3xl">What users can expect from publishing cadence, support, incident handling, corrections and planned service changes.</p></div></header>
      <div className="page-shell py-12 max-w-5xl space-y-10 text-sm leading-7 text-[var(--ink2)]">
        <section><h2 className="ua-h3 text-[var(--ink)]">Support</h2><p className="mt-3">Primary contact: <a href="mailto:support@urdatlas.com" className="text-link">support@urdatlas.com</a>. Public reply target: 2–4 business days. Credible security reports have a separate acknowledgement target documented at <Link href="/security/reporting" className="text-link">Responsible Disclosure</Link>.</p><p className="mt-3">For a production-impacting data/API report, include chain, observation date, endpoint/path, returned status/error, and enough detail to reproduce the issue without sharing secret credentials.</p></section>
        <section><h2 className="ua-h3 text-[var(--ink)]">Daily publication windows</h2><p className="mt-3">Primary production windows are approximately <strong>08:00 and 20:00 Europe/Oslo</strong>. Scheduler catch-up checks run after each primary window so a missed GitHub scheduled trigger does not depend on one single cron event. Catch-up checks should not start duplicate heavy pipeline runs when the relevant window has already published.</p><p className="mt-3">These are operating targets, not a contractual timestamp SLA. Bitcoin/Ethereum are expected around a one-day observation lag; Arbitrum/Base around seven days, subject to upstream source availability.</p></section>
        <section><h2 className="ua-h3 text-[var(--ink)]">Incident classes</h2><ul className="mt-3 list-disc pl-5 space-y-2"><li><strong>Freshness/upstream:</strong> no sufficiently new upstream source day exists.</li><li><strong>Publication:</strong> expected artifact missing, malformed, stale beyond policy or inconsistent with the published methodology.</li><li><strong>Access/billing:</strong> entitlement or customer-portal behavior is incorrect.</li><li><strong>Security/privacy:</strong> suspected unauthorized access, credential exposure or personal-data/security incident.</li></ul><p className="mt-3">These classes are communicated separately so an upstream data delay is not mislabeled as a security incident and a failed pipeline is not represented as a successful publication.</p></section>
        <section><h2 className="ua-h3 text-[var(--ink)]">Corrections and revisions</h2><p className="mt-3">Corrections affecting archived artifacts should produce a changelog/correction entry stating the affected chains/dates/fields, whether methodology changed, whether historical files were regenerated and whether customers should re-pull cached artifacts.</p><p className="mt-3">See <Link href="/methodology/changelog" className="text-link">Methodology Changelog</Link>, <Link href="/methodology/provenance" className="text-link">Provenance & Revisions</Link> and <Link href="/api-docs/versioning" className="text-link">Versioning</Link>.</p></section>
        <section><h2 className="ua-h3 text-[var(--ink)]">Planned wind-down</h2><p className="mt-3">For a planned permanent discontinuation, Urd Atlas targets at least 30 calendar days&apos; notice where reasonably practicable and a reasonable export window for active subscribers to retrieve data within their current entitlement. Already lawfully downloaded subscriber files remain subject to the retention and license terms in the <Link href="/terms" className="text-link">Terms of Service</Link>.</p></section>
        <section><h2 className="ua-h3 text-[var(--ink)]">Fit</h2><p className="mt-3">Urd Atlas is not an intraday execution feed. It is designed for descriptive regime conditioning, monitoring, historical segmentation, reporting and data/model workflows where a daily or slower chain-specific context layer is appropriate.</p></section>
      </div>
    </main>
  );
}
